version: "3.5"

services:
  webserver:
    build:
      context: ./bin/${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-${PHP_VERSION}
    restart: "always"
    ports:
      - "${HOST_MACHINE_PORT}:80"
    depends_on:
      - ursa_mysql
    volumes:
      - ./src:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    networks:
      - "ursa_network"

  activemq:
    image: kharis/activemq:latest
    container_name: ursa_activemq
    restart: "always"
    ports:
      - "8161:8161"
      - "5672:5672"
      - "1883:1883"
      - "9876:61613"
    networks:
      - "ursa_network"

  ursa_mysql:
    image: mysql:latest
    container_name: ursa_mysql
    restart: "always"
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - "ursa_network"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql

networks:
  ursa_network:
    driver: bridge
